name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:        
        artifact: 'TestResult'
        name: ".NET tests"
        reporter: dotnet-trx
        path: "**/*.trx"